# Generated by Django 5.0.6 on 2024-06-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingmst',
            name='country_ref_id',
        ),
        migrations.AddField(
            model_name='billingmst',
            name='currency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billingmst',
            name='discount_amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billingmst',
            name='discount_rate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billingmst',
            name='tax_amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='billingmst',
            name='tax_rate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
